AEDA_2_FINAL: Condominios.cpp File Reference
Condominios.cpp File Reference
#include "Condominios.h"
#include <iostream>
#include <windows.h>
Functions
bool ordhabarea (Habitacao *a, Habitacao *b)
bool ordhabmorada (Habitacao *a, Habitacao *b)
bool ordhabmensalidade (Habitacao *a, Habitacao *b)
void limpa ()
Function Documentation
void limpa ()
Definition at line 128 of file Condominios.cpp.
Referenced by Condominio::verHab().
bool ordhabarea (Habitacao * a, Habitacao * b)
Definition at line 86 of file Condominios.cpp.
References Habitacao::getA_Habitacional().
Referenced by Condominio::OrdenarHabArea().
bool ordhabmensalidade (Habitacao * a, Habitacao * b)
Definition at line 100 of file Condominios.cpp.
References Habitacao::getMensalidade().
Referenced by Condominio::OrdenarHabMensalidade().
bool ordhabmorada (Habitacao * a, Habitacao * b)
Definition at line 93 of file Condominios.cpp.
References Habitacao::getMorada().
Referenced by Condominio::OrdenarHabMorada().