AEDA_2_FINAL: Menu.cpp File Reference
Menu.cpp File Reference
#include "Menu.h"
#include <iostream>
#include <conio.h>
#include <windows.h>
Macros
#define BLACK 0
#define BLUE 1
#define GREEN 2
#define CYAN 3
#define RED 4
#define MAGENTA 5
#define BROWN 6
#define LIGHTGRAY 7
#define DARKGRAY 8
#define LIGHTBLUE 9
#define LIGHTGREEN 10
#define LIGHTCYAN 11
#define LIGHTRED 12
#define LIGHTMAGENTA 13
#define YELLOW 14
#define WHITE 15
Functions
void clrscr ()
void setcolor (unsigned int color, unsigned int background_color)
bool verificaTipo (string opcao)
Macro Definition Documentation
#define BLACK 0
Definition at line 11 of file Menu.cpp.
Referenced by Menu::DrawnM_op1(), Menu::DrawnM_op2(), Menu::DrawnM_op3(), Menu::DrawnM_op4(), Menu::DrawnM_op5(), Menu::DrawnS1_Hab_op1(), Menu::DrawnS1_Hab_op1_apartamento(), Menu::DrawnS1_Hab_op1_vivenda(), Menu::DrawnS1_Hab_op1_voltar(), Menu::DrawnS1_Hab_op2(), Menu::DrawnS1_Hab_op3(), Menu::DrawnS1_Hab_op3_Aderir_Servico(), Menu::DrawnS1_Hab_op3_Mod_AreaHabitacional(), Menu::DrawnS1_Hab_op3_Mod_Mensalidade(), Menu::DrawnS1_Hab_op3_Terminar_Servico(), Menu::DrawnS1_Hab_op3_Voltar(), Menu::DrawnS1_Hab_op4(), Menu::DrawnS1_op1(), Menu::DrawnS1_op2(), Menu::DrawnS1_op3(), Menu::DrawnS1_op4(), Menu::DrawnS1_op5(), Menu::DrawnS1_op6(), Menu::DrawnS1_Ser_op1(), Menu::DrawnS1_Ser_op2(), Menu::DrawnS1_Ser_op3(), Menu::DrawnS1_Ser_op4(), Menu::DrawnTop1(), Menu::DrawnTop2(), Menu::DrawnTop3(), Menu::DrawnTop4(), Menu::DrawnTop5(), and setcolor().
#define BLUE 1
Definition at line 12 of file Menu.cpp.
#define BROWN 6
Definition at line 17 of file Menu.cpp.
#define CYAN 3
Definition at line 14 of file Menu.cpp.
#define DARKGRAY 8
Definition at line 19 of file Menu.cpp.
#define GREEN 2
Definition at line 13 of file Menu.cpp.
#define LIGHTBLUE 9
Definition at line 20 of file Menu.cpp.
#define LIGHTCYAN 11
Definition at line 22 of file Menu.cpp.
#define LIGHTGRAY 7
Definition at line 18 of file Menu.cpp.
Referenced by Menu::DrawnM_op1(), Menu::DrawnM_op2(), Menu::DrawnM_op3(), Menu::DrawnM_op4(), Menu::DrawnM_op5(), Menu::DrawnS1_Hab_op1(), Menu::DrawnS1_Hab_op1_apartamento(), Menu::DrawnS1_Hab_op1_vivenda(), Menu::DrawnS1_Hab_op1_voltar(), Menu::DrawnS1_Hab_op2(), Menu::DrawnS1_Hab_op3(), Menu::DrawnS1_Hab_op3_Aderir_Servico(), Menu::DrawnS1_Hab_op3_Mod_AreaHabitacional(), Menu::DrawnS1_Hab_op3_Mod_Mensalidade(), Menu::DrawnS1_Hab_op3_Terminar_Servico(), Menu::DrawnS1_Hab_op3_Voltar(), Menu::DrawnS1_Hab_op4(), Menu::DrawnS1_op1(), Menu::DrawnS1_op2(), Menu::DrawnS1_op3(), Menu::DrawnS1_op4(), Menu::DrawnS1_op5(), Menu::DrawnS1_op6(), Menu::DrawnS1_Ser_op1(), Menu::DrawnS1_Ser_op2(), Menu::DrawnS1_Ser_op3(), Menu::DrawnS1_Ser_op4(), Menu::DrawnTop1(), Menu::DrawnTop2(), Menu::DrawnTop3(), Menu::DrawnTop4(), and Menu::DrawnTop5().
#define LIGHTGREEN 10
Definition at line 21 of file Menu.cpp.
#define LIGHTMAGENTA 13
Definition at line 24 of file Menu.cpp.
#define LIGHTRED 12
Definition at line 23 of file Menu.cpp.
#define MAGENTA 5
Definition at line 16 of file Menu.cpp.
#define RED 4
Definition at line 15 of file Menu.cpp.
#define WHITE 15
Definition at line 26 of file Menu.cpp.
Referenced by Menu::DrawnM_op1(), Menu::DrawnM_op2(), Menu::DrawnM_op3(), Menu::DrawnM_op4(), Menu::DrawnM_op5(), Menu::DrawnS1_Hab_op1(), Menu::DrawnS1_Hab_op1_apartamento(), Menu::DrawnS1_Hab_op1_vivenda(), Menu::DrawnS1_Hab_op1_voltar(), Menu::DrawnS1_Hab_op2(), Menu::DrawnS1_Hab_op3(), Menu::DrawnS1_Hab_op3_Aderir_Servico(), Menu::DrawnS1_Hab_op3_Mod_AreaHabitacional(), Menu::DrawnS1_Hab_op3_Mod_Mensalidade(), Menu::DrawnS1_Hab_op3_Terminar_Servico(), Menu::DrawnS1_Hab_op3_Voltar(), Menu::DrawnS1_Hab_op4(), Menu::DrawnS1_op1(), Menu::DrawnS1_op2(), Menu::DrawnS1_op3(), Menu::DrawnS1_op4(), Menu::DrawnS1_op5(), Menu::DrawnS1_op6(), Menu::DrawnS1_Ser_op1(), Menu::DrawnS1_Ser_op2(), Menu::DrawnS1_Ser_op3(), Menu::DrawnS1_Ser_op4(), Menu::DrawnTop1(), Menu::DrawnTop2(), Menu::DrawnTop3(), Menu::DrawnTop4(), and Menu::DrawnTop5().
#define YELLOW 14
Definition at line 25 of file Menu.cpp.
Function Documentation
void clrscr ()
Definition at line 30 of file Menu.cpp.
Referenced by Menu::DrawnM_op1(), Menu::DrawnM_op2(), Menu::DrawnM_op3(), Menu::DrawnM_op4(), Menu::DrawnM_op5(), Menu::DrawnMenuI(), Menu::DrawnS1_Hab_op1(), Menu::DrawnS1_Hab_op1_apartamento(), Menu::DrawnS1_Hab_op1_vivenda(), Menu::DrawnS1_Hab_op1_voltar(), Menu::DrawnS1_Hab_op2(), Menu::DrawnS1_Hab_op3(), Menu::DrawnS1_Hab_op3_Aderir_Servico(), Menu::DrawnS1_Hab_op3_Mod_AreaHabitacional(), Menu::DrawnS1_Hab_op3_Mod_Mensalidade(), Menu::DrawnS1_Hab_op3_Terminar_Servico(), Menu::DrawnS1_Hab_op3_Voltar(), Menu::DrawnS1_Hab_op4(), Menu::DrawnS1_op1(), Menu::DrawnS1_op2(), Menu::DrawnS1_op3(), Menu::DrawnS1_op4(), Menu::DrawnS1_op5(), Menu::DrawnS1_op6(), Menu::DrawnS1_Ser_op1(), Menu::DrawnS1_Ser_op2(), Menu::DrawnS1_Ser_op3(), Menu::DrawnS1_Ser_op4(), Menu::DrawnTop1(), Menu::DrawnTop2(), Menu::DrawnTop3(), Menu::DrawnTop4(), Menu::DrawnTop5(), Menu::Hab_op1_apartamento(), Menu::Hab_op1_vivenda(), Menu::Hab_op3_Aderir_Servico(), Menu::Hab_op3_Mod_AreaHabitacional(), Menu::Hab_op3_Mod_Mensalidade(), Menu::Hab_op3_Terminar_Servico(), Menu::M_op1(), Menu::M_op2(), Menu::M_op3(), Menu::M_op4(), Menu::S1_Hab_op2(), Menu::S1_op1(), Menu::S1_op2(), Menu::S1_Ser_op3(), Menu::Tra_op1(), Menu::Tra_op2(), Menu::Tra_op3(), and Menu::Tra_op4().
void setcolor (unsigned int color, unsigned int background_color)
Definition at line 45 of file Menu.cpp.
References BLACK.
Referenced by Menu::DrawnM_op1(), Menu::DrawnM_op2(), Menu::DrawnM_op3(), Menu::DrawnM_op4(), Menu::DrawnM_op5(), Menu::DrawnS1_Hab_op1(), Menu::DrawnS1_Hab_op1_apartamento(), Menu::DrawnS1_Hab_op1_vivenda(), Menu::DrawnS1_Hab_op1_voltar(), Menu::DrawnS1_Hab_op2(), Menu::DrawnS1_Hab_op3(), Menu::DrawnS1_Hab_op3_Aderir_Servico(), Menu::DrawnS1_Hab_op3_Mod_AreaHabitacional(), Menu::DrawnS1_Hab_op3_Mod_Mensalidade(), Menu::DrawnS1_Hab_op3_Terminar_Servico(), Menu::DrawnS1_Hab_op3_Voltar(), Menu::DrawnS1_Hab_op4(), Menu::DrawnS1_op1(), Menu::DrawnS1_op2(), Menu::DrawnS1_op3(), Menu::DrawnS1_op4(), Menu::DrawnS1_op5(), Menu::DrawnS1_op6(), Menu::DrawnS1_Ser_op1(), Menu::DrawnS1_Ser_op2(), Menu::DrawnS1_Ser_op3(), Menu::DrawnS1_Ser_op4(), Menu::DrawnTop1(), Menu::DrawnTop2(), Menu::DrawnTop3(), Menu::DrawnTop4(), and Menu::DrawnTop5().
bool verificaTipo (string opcao)
Definition at line 585 of file Menu.cpp.
Referenced by Menu::Hab_op1_apartamento().