AEDA_2_FINAL: Vivenda Class Reference
Vivenda Class Reference
#include <Vivenda.h>
Public Member Functions
Vivenda (string morada, unsigned int area_hab, float mensalidade, unsigned int area_ext, bool piscina)
~Vivenda ()
void info ()
void calcMensalidade ()
unsigned int getAreaExterior ()
void adicionaPiscina ()
void removePiscina ()
void modificaArea_Exterior (unsigned int areaExt)
string save ()
Public Member Functions inherited from Habitacao
Habitacao (string morada, unsigned int area_hab, float mensalidade)
void modificaMensalidade (float mensalidade)
string getMorada ()
unsigned int getA_Habitacional ()
float getMensalidade ()
Condomino * getCondomino ()
vector< Servico * > getServicos ()
void modificaMorada (string morada)
void modificaArea_Habitacional (unsigned int areaHab)
void ordenaServicosNome ()
void addCondomino (Condomino *cond)
void addServico (Servico *ser)
void removeServico (Servico *ser)
void verServicosAderidos ()
Private Attributes
unsigned int Area_Exterior
bool Piscina
Detailed Description
Definition at line 10 of file Vivenda.h.
Constructor & Destructor Documentation
Vivenda::Vivenda (string morada, unsigned int area_hab, float mensalidade, unsigned int area_ext, bool piscina)
Constructor da class Vivenda, cria uma vivenda com as expecificacoes dadas
Parameters
morada Morada (Habitacao::Morada)
area_hab Area da Habitacao (Habitacao::Area_Habitacional)
mensalidade Mensalidade (Habitacao::Mensalidade)
area_ext Area exterior (Vivenda::Area_Exterior)
piscina Se tem piscina ou nao (Vivenda::Piscina)
Definition at line 7 of file Vivenda.cpp.
Vivenda::~Vivenda ()
Destrutor da class Vivenda
Member Function Documentation
void Vivenda::adicionaPiscina ()
Adiciona uma piscina a vivenda
Definition at line 15 of file Vivenda.cpp.
References Piscina.
void Vivenda::calcMensalidade () virtual
Calcula a mensalidade (Habitacao::Mensalidade) da vivenda
Implements Habitacao.
Definition at line 46 of file Vivenda.cpp.
References Area_Exterior, Habitacao::getA_Habitacional(), Habitacao::getMensalidade(), Habitacao::modificaMensalidade(), and Piscina.
unsigned int Vivenda::getAreaExterior ()
Devolve a area exterior (Vivenda::Area_Exterior) da vivenda
Definition at line 10 of file Vivenda.cpp.
References Area_Exterior.
Referenced by info().
void Vivenda::info () virtual
Devolve a informacao sobre a Vivenda
Implements Habitacao.
Definition at line 25 of file Vivenda.cpp.
References Habitacao::getA_Habitacional(), getAreaExterior(), Habitacao::getCondomino(), Habitacao::getMensalidade(), Habitacao::getMorada(), Condomino::getNif(), Condomino::getNome(), Habitacao::getServicos(), and Piscina.
void Vivenda::modificaArea_Exterior (unsigned int areaExt)
Modifica a area exterior (Vivenda::Area_Exterior) da vivenda para a area pretendida
Parameters
areaExt Area exterior pretendida
Definition at line 65 of file Vivenda.cpp.
References Area_Exterior.
void Vivenda::removePiscina ()
Remove piscina da vivenda
Definition at line 20 of file Vivenda.cpp.
References Piscina.
string Vivenda::save () virtual
Guarda a informacao
Reimplemented from Habitacao.
Definition at line 73 of file Vivenda.cpp.
References Area_Exterior, Habitacao::getA_Habitacional(), Habitacao::getCondomino(), Habitacao::getMensalidade(), Habitacao::getMorada(), Condomino::getNome(), Habitacao::getServicos(), and Piscina.
Member Data Documentation
unsigned int Vivenda::Area_Exterior private
Area exterior da vivenda
Definition at line 59 of file Vivenda.h.
Referenced by calcMensalidade(), getAreaExterior(), modificaArea_Exterior(), and save().
bool Vivenda::Piscina private
Piscina da vivenda (true = Tem piscina / false = Nao tem piscina)
Definition at line 63 of file Vivenda.h.
Referenced by adicionaPiscina(), calcMensalidade(), info(), removePiscina(), and save().
The documentation for this class was generated from the following files:
Vivenda.h
Vivenda.cpp