AEDA_2_FINAL: Data Class Reference
Data Class Reference
#include <Data.h>
Public Member Functions
Data ()
void inicialize ()
void savecond ()
bool run ()
Condomino * getCondomino (int nif)
Servico * getServico (int serv)
Condominio * getCondominio (string nome)
void info ()
void remCondominio (string nome)
void remServico (string nome)
void addCond (string nome, string localizacao)
void saveServicos ()
void saveTransportes ()
void saveHabitacoes ()
void addCondArv (Condominio *cond)
void remCondArv (Condominio *cond)
BST< Condominio * > getArvCondominios ()
vector< Condominio * > ordenaHabitacao ()
void refresharv ()
void remCondominioArv (string nome)
void addCondArv (string nome, string localizacao)
void pointerToCond ()
vector< Condominio > condXHab (int x)
vector< Condominio > condEntreHab (int x, int y)
vector< Condominio > condLocal (string local)
vector< Condominio > condXVivendas (int x)
vector< Condominio > condXApartamentos (int x)
Condominio condNome (string Nome)
Private Attributes
vector< Condominio * > Condominios
vector< Servico * > Servicos
vector< Condomino * > Condominos
BST< Condominio * > arvCondominios
BST< Condominio > arvore
Detailed Description
Definition at line 10 of file Data.h.
Constructor & Destructor Documentation
Data::Data () inline
Construtor da class, inicializa as arvores;
Definition at line 37 of file Data.h.
Member Function Documentation
void Data::addCond (string nome, string localizacao)
Adiciona Condominio de nome (Condominio::Nome) pretendido ao vector de condominios (Data::Condominios)
Parameters
nome Nome pretendido
Definition at line 107 of file Data.cpp.
void Data::addCondArv (Condominio * cond)
Adiciona condominio cond á arvore de apontadores de Condominio
Definition at line 965 of file Data.cpp.
void Data::addCondArv (string nome, string localizacao)
Adiciona condominio com as explicacoes dadas a arvore de apontadores de Condominio
Definition at line 996 of file Data.cpp.
vector< Condominio > Data::condEntreHab (int x, int y)
Retorna vector ordenado de condominios com numero de habitacoes entre x e y;
Definition at line 1026 of file Data.cpp.
References BSTItrIn< Comparable >::advance(), Condominio::getNumHab(), BSTItrIn< Comparable >::isAtEnd(), and BSTItrIn< Comparable >::retrieve().
vector< Condominio > Data::condLocal (string local)
Retorna vector ordenado de condominios de localidade local;
Definition at line 1040 of file Data.cpp.
References BSTItrIn< Comparable >::advance(), Condominio::getLocalizacao(), BSTItrIn< Comparable >::isAtEnd(), and BSTItrIn< Comparable >::retrieve().
Condominio Data::condNome (string Nome)
Retorna o condominio de nome Nome;
Definition at line 1082 of file Data.cpp.
References BSTItrIn< Comparable >::advance(), Condominio::getNome(), BSTItrIn< Comparable >::isAtEnd(), and BSTItrIn< Comparable >::retrieve().
vector< Condominio > Data::condXApartamentos (int x)
Retorna vector ordenado de condominios com x Apartamentos;
Definition at line 1068 of file Data.cpp.
References BSTItrIn< Comparable >::advance(), Condominio::getNumHab(), Condominio::getNumVivendas(), BSTItrIn< Comparable >::isAtEnd(), and BSTItrIn< Comparable >::retrieve().
vector< Condominio > Data::condXHab (int x)
Retorna vector ordenado de condominios com x habitacoes;
Definition at line 1011 of file Data.cpp.
References BSTItrIn< Comparable >::advance(), Condominio::getNumHab(), BSTItrIn< Comparable >::isAtEnd(), and BSTItrIn< Comparable >::retrieve().
vector< Condominio > Data::condXVivendas (int x)
Retorna vector ordenado de condominios com x vivendas;
Definition at line 1054 of file Data.cpp.
References BSTItrIn< Comparable >::advance(), Condominio::getNumVivendas(), BSTItrIn< Comparable >::isAtEnd(), and BSTItrIn< Comparable >::retrieve().
BST< Condominio * > Data::getArvCondominios ()
Retorna a arvore de apontadores de Condominio
Definition at line 989 of file Data.cpp.
Condominio * Data::getCondominio (string nome)
Devolve o Condominio com o nome (Condominio::Nome) pretendido
Parameters
nome Nome pretendido
Definition at line 70 of file Data.cpp.
Condomino * Data::getCondomino (int nif)
Devolve o condomino cujo NIF (Condomino::NIF) é o pretendido
Parameters
nif NIF pretendido
Definition at line 13 of file Data.cpp.
Servico * Data::getServico (int serv)
Devolve o Servico que se encontra na posicao pretendida no vector de servicos (Data::Servico)
Parameters
serv Posicao pretendida
Definition at line 23 of file Data.cpp.
void Data::info ()
Devolve a informacao sobre os condominio, servicos, e condominos existentes
Definition at line 39 of file Data.cpp.
References BSTItrIn< Comparable >::advance(), Condominio::getLocalizacao(), Condominio::getNome(), Condominio::getNumHab(), BSTItrIn< Comparable >::isAtEnd(), and BSTItrIn< Comparable >::retrieve().
void Data::inicialize ()
Recolhe dos ficheiros de texto a informacao necessaria
Definition at line 592 of file Data.cpp.
References Habitacao::addCondomino(), and Habitacao::addServico().
Referenced by main().
vector< Condominio * > Data::ordenaHabitacao ()
Retorna vector de apontadores de Condominio ordenado por numero crescente de habitacoes
Definition at line 937 of file Data.cpp.
References BSTItrLevel< Comparable >::advance(), BSTItrLevel< Comparable >::isAtEnd(), and BSTItrLevel< Comparable >::retrieve().
void Data::pointerToCond ()
Passa da arvore de apontadores de Condominio para a arvore de Condominio (s)
Definition at line 29 of file Data.cpp.
References BSTItrIn< Comparable >::advance(), BSTItrIn< Comparable >::isAtEnd(), and BSTItrIn< Comparable >::retrieve().
void Data::refresharv ()
Actualiza arvore de habitadores de Condominio
Definition at line 953 of file Data.cpp.
References BSTItrLevel< Comparable >::advance(), BST< Comparable >::insert(), BSTItrLevel< Comparable >::isAtEnd(), and BSTItrLevel< Comparable >::retrieve().
void Data::remCondArv (Condominio * cond)
Remove condominio cond da arvore de apontadores de Condominio
Definition at line 969 of file Data.cpp.
void Data::remCondominio (string nome)
Remove Condominio de nome (Condominio::Nome) pretendido do vector de condominios (Data::Condominios)
Parameters
nome Nome pretendido
Definition at line 80 of file Data.cpp.
void Data::remCondominioArv (string nome)
Remove condominio de nome nome da arvore de apontadores de Condominio
Definition at line 975 of file Data.cpp.
void Data::remServico (string nome)
Remove Servico de nome (Servico::Nome) pretendido do vector de servicos (Data::Servicos)
Definition at line 94 of file Data.cpp.
bool Data::run ()
Metodo para gerir todos os condominios
void Data::savecond ()
Guarda nos ficheiros de texto a informacao
Definition at line 833 of file Data.cpp.
void Data::saveHabitacoes ()
Guarda as alteracoes efectuadas no que conta a Habitacoes
Definition at line 910 of file Data.cpp.
void Data::saveServicos ()
Guarda as alteracoes efectuadas no que conta a servicos
Definition at line 858 of file Data.cpp.
void Data::saveTransportes ()
Guarda as alteracoes efectuadas no que conta a Transportes
Definition at line 884 of file Data.cpp.
Member Data Documentation
BST<Condominio*> Data::arvCondominios private
Arvore (BST) com apontadores para os condominios
Definition at line 27 of file Data.h.
BST<Condominio> Data::arvore private
Arvore com os condomios
Definition at line 31 of file Data.h.
vector<Condominio *> Data::Condominios private
Vector de Condominio (s)
Definition at line 15 of file Data.h.
vector<Condomino *> Data::Condominos private
Vector de Condomino (s)
Definition at line 23 of file Data.h.
vector<Servico *> Data::Servicos private
Vector de Servico (s)
Definition at line 19 of file Data.h.
The documentation for this class was generated from the following files:
Data.h
Data.cpp