AEDA_2_FINAL: Menu Class Reference
Menu Class Reference
#include <Menu.h>
Public Member Functions
Menu ()
~Menu ()
int Iniciar (Data &data)
void navMenus (int tecla, unsigned int Num_de_Opcoes, unsigned int &op)
void DrawnMenuI ()
void save ()
int M_op1 ()
int M_op2 ()
int M_op3 ()
int M_op4 ()
void DrawnM_op1 ()
void DrawnM_op2 ()
void DrawnM_op3 ()
void DrawnM_op4 ()
void DrawnM_op5 ()
void S1_iniciar ()
int S1_op1 ()
int S1_op2 ()
int S1_op3 ()
int S1_op4 ()
int S1_op5 ()
void DrawnS1_op1 ()
void DrawnS1_op2 ()
void DrawnS1_op3 ()
void DrawnS1_op4 ()
void DrawnS1_op5 ()
void DrawnS1_op6 ()
void S1_Hab_Iniciar ()
int S1_Hab_op1 ()
int S1_Hab_op2 ()
int S1_Hab_op3 ()
void DrawnS1_Hab_op1 ()
void DrawnS1_Hab_op2 ()
void DrawnS1_Hab_op3 ()
void DrawnS1_Hab_op4 ()
void Hab_op1_iniciar ()
int Hab_op1_vivenda ()
int Hab_op1_apartamento ()
void DrawnS1_Hab_op1_vivenda ()
void DrawnS1_Hab_op1_apartamento ()
void DrawnS1_Hab_op1_voltar ()
void Hab_op3_iniciar ()
int Hab_op3_Mod_Mensalidade ()
int Hab_op3_Mod_AreaHabitacional ()
int Hab_op3_Aderir_Servico ()
int Hab_op3_Terminar_Servico ()
void DrawnS1_Hab_op3_Mod_Mensalidade ()
void DrawnS1_Hab_op3_Mod_AreaHabitacional ()
void DrawnS1_Hab_op3_Aderir_Servico ()
void DrawnS1_Hab_op3_Terminar_Servico ()
void DrawnS1_Hab_op3_Voltar ()
void S1_Ser_Iniciar ()
int S1_Ser_op1 ()
int S1_Ser_op2 ()
int S1_Ser_op3 ()
void DrawnS1_Ser_op1 ()
void DrawnS1_Ser_op2 ()
void DrawnS1_Ser_op3 ()
void DrawnS1_Ser_op4 ()
void Transportes_iniciar ()
int Tra_op1 ()
int Tra_op2 ()
int Tra_op3 ()
int Tra_op4 ()
void DrawnTop1 ()
void DrawnTop2 ()
void DrawnTop3 ()
void DrawnTop4 ()
void DrawnTop5 ()
Private Attributes
Data data
string condAgerir
Condominio * CondaGerir
unsigned int Nopcao_M = 1
unsigned int NumOpcoes_M = 5
unsigned int Nopcao_S1 = 1
unsigned int NumOpcoes_S1 = 6
unsigned int Nopcao_S1_H = 1
unsigned int NumOpcoes_S1_H = 4
unsigned int Nopcao_S1_H_A = 1
unsigned int NumOpcoes_S1_H_A = 3
unsigned int Nopcao_S1_H_M = 1
unsigned int NumOpcoes_S1_H_M = 5
unsigned int Nopcao_S1_S = 1
unsigned int NumOpcoes_S1_S = 4
unsigned int Nopcao_T = 1
unsigned int NumOpcoes_T = 5
Detailed Description
Definition at line 10 of file Menu.h.
Constructor & Destructor Documentation
Menu::Menu ()
Definition at line 55 of file Menu.cpp.
Menu::~Menu ()
Definition at line 61 of file Menu.cpp.
Member Function Documentation
void Menu::DrawnM_op1 ()
Definition at line 90 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnM_op2 ()
Definition at line 101 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnM_op3 ()
Definition at line 112 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnM_op4 ()
Definition at line 123 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnM_op5 ()
Definition at line 134 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnMenuI ()
Definition at line 65 of file Menu.cpp.
References clrscr().
void Menu::DrawnS1_Hab_op1 ()
Definition at line 454 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_Hab_op1_apartamento ()
Definition at line 649 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_Hab_op1_vivenda ()
Definition at line 639 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_Hab_op1_voltar ()
Definition at line 659 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_Hab_op2 ()
Definition at line 464 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_Hab_op3 ()
Definition at line 474 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_Hab_op3_Aderir_Servico ()
Definition at line 867 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_Hab_op3_Mod_AreaHabitacional ()
Definition at line 855 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_Hab_op3_Mod_Mensalidade ()
Definition at line 843 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_Hab_op3_Terminar_Servico ()
Definition at line 879 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_Hab_op3_Voltar ()
Definition at line 891 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_Hab_op4 ()
Definition at line 484 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_op1 ()
Definition at line 298 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_op2 ()
Definition at line 311 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_op3 ()
Definition at line 324 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_op4 ()
Definition at line 337 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_op5 ()
Definition at line 350 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_op6 ()
Definition at line 363 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_Ser_op1 ()
Definition at line 1036 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_Ser_op2 ()
Definition at line 1046 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_Ser_op3 ()
Definition at line 1056 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnS1_Ser_op4 ()
Definition at line 1066 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnTop1 ()
Definition at line 1210 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnTop2 ()
Definition at line 1222 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnTop3 ()
Definition at line 1235 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnTop4 ()
Definition at line 1248 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
void Menu::DrawnTop5 ()
Definition at line 1260 of file Menu.cpp.
References BLACK, clrscr(), LIGHTGRAY, setcolor(), and WHITE.
int Menu::Hab_op1_apartamento ()
Definition at line 593 of file Menu.cpp.
References Habitacao::addCondomino(), Habitacao::calcMensalidade(), clrscr(), and verificaTipo().
void Menu::Hab_op1_iniciar ()
Definition at line 495 of file Menu.cpp.
References ENTER, and ESC.
int Menu::Hab_op1_vivenda ()
Definition at line 542 of file Menu.cpp.
References Habitacao::addCondomino(), Habitacao::calcMensalidade(), and clrscr().
int Menu::Hab_op3_Aderir_Servico ()
Definition at line 781 of file Menu.cpp.
References Habitacao::addServico(), and clrscr().
void Menu::Hab_op3_iniciar ()
Definition at line 670 of file Menu.cpp.
References ENTER, and ESC.
int Menu::Hab_op3_Mod_AreaHabitacional ()
Definition at line 755 of file Menu.cpp.
References clrscr(), and Habitacao::modificaArea_Habitacional().
int Menu::Hab_op3_Mod_Mensalidade ()
Definition at line 729 of file Menu.cpp.
References clrscr(), and Habitacao::modificaMensalidade().
int Menu::Hab_op3_Terminar_Servico ()
Definition at line 813 of file Menu.cpp.
References clrscr(), Habitacao::removeServico(), and Habitacao::verServicosAderidos().
int Menu::Iniciar (Data & data)
Definition at line 1274 of file Menu.cpp.
References ENTER, and ESC.
Referenced by main().
int Menu::M_op1 ()
Definition at line 145 of file Menu.cpp.
References clrscr().
int Menu::M_op2 ()
Definition at line 152 of file Menu.cpp.
References clrscr().
int Menu::M_op3 ()
Definition at line 158 of file Menu.cpp.
References clrscr().
int Menu::M_op4 ()
Definition at line 171 of file Menu.cpp.
References clrscr().
void Menu::navMenus (int tecla, unsigned int Num_de_Opcoes, unsigned int & op)
Definition at line 75 of file Menu.cpp.
void Menu::S1_Hab_Iniciar ()
Definition at line 380 of file Menu.cpp.
References ENTER, and ESC.
int Menu::S1_Hab_op1 ()
Definition at line 433 of file Menu.cpp.
int Menu::S1_Hab_op2 ()
Definition at line 438 of file Menu.cpp.
References clrscr().
int Menu::S1_Hab_op3 ()
Definition at line 449 of file Menu.cpp.
void Menu::S1_iniciar ()
Definition at line 183 of file Menu.cpp.
References ENTER, and ESC.
int Menu::S1_op1 ()
Definition at line 256 of file Menu.cpp.
References clrscr().
int Menu::S1_op2 ()
Definition at line 269 of file Menu.cpp.
References clrscr().
int Menu::S1_op3 ()
Definition at line 283 of file Menu.cpp.
int Menu::S1_op4 ()
Definition at line 288 of file Menu.cpp.
int Menu::S1_op5 ()
Definition at line 293 of file Menu.cpp.
void Menu::S1_Ser_Iniciar ()
Definition at line 908 of file Menu.cpp.
References ENTER, and ESC.
int Menu::S1_Ser_op1 ()
Definition at line 960 of file Menu.cpp.
int Menu::S1_Ser_op2 ()
Definition at line 982 of file Menu.cpp.
int Menu::S1_Ser_op3 ()
Definition at line 998 of file Menu.cpp.
References clrscr(), Servico::modificaNome(), and Servico::modificaNPS().
void Menu::save ()
Definition at line 1341 of file Menu.cpp.
Referenced by main().
int Menu::Tra_op1 ()
Definition at line 1143 of file Menu.cpp.
References clrscr().
int Menu::Tra_op2 ()
Definition at line 1163 of file Menu.cpp.
References clrscr().
int Menu::Tra_op3 ()
Definition at line 1177 of file Menu.cpp.
References clrscr().
int Menu::Tra_op4 ()
Definition at line 1190 of file Menu.cpp.
References clrscr().
void Menu::Transportes_iniciar ()
Definition at line 1085 of file Menu.cpp.
References ENTER, and ESC.
Member Data Documentation
string Menu::condAgerir private
Definition at line 103 of file Menu.h.
Condominio* Menu::CondaGerir private
Definition at line 104 of file Menu.h.
Data Menu::data private
Definition at line 102 of file Menu.h.
unsigned int Menu::Nopcao_M = 1 private
Definition at line 107 of file Menu.h.
unsigned int Menu::Nopcao_S1 = 1 private
Definition at line 111 of file Menu.h.
unsigned int Menu::Nopcao_S1_H = 1 private
Definition at line 115 of file Menu.h.
unsigned int Menu::Nopcao_S1_H_A = 1 private
Definition at line 119 of file Menu.h.
unsigned int Menu::Nopcao_S1_H_M = 1 private
Definition at line 123 of file Menu.h.
unsigned int Menu::Nopcao_S1_S = 1 private
Definition at line 127 of file Menu.h.
unsigned int Menu::Nopcao_T = 1 private
Definition at line 132 of file Menu.h.
unsigned int Menu::NumOpcoes_M = 5 private
Definition at line 108 of file Menu.h.
unsigned int Menu::NumOpcoes_S1 = 6 private
Definition at line 112 of file Menu.h.
unsigned int Menu::NumOpcoes_S1_H = 4 private
Definition at line 116 of file Menu.h.
unsigned int Menu::NumOpcoes_S1_H_A = 3 private
Definition at line 120 of file Menu.h.
unsigned int Menu::NumOpcoes_S1_H_M = 5 private
Definition at line 124 of file Menu.h.
unsigned int Menu::NumOpcoes_S1_S = 4 private
Definition at line 128 of file Menu.h.
unsigned int Menu::NumOpcoes_T = 5 private
Definition at line 133 of file Menu.h.
The documentation for this class was generated from the following files:
Menu.h
Menu.cpp