AEDA_2_FINAL: Condominio Class Reference
Condominio Class Reference
#include <Condominios.h>
Public Member Functions
Condominio (string nome)
void addHabitacao (Habitacao *hab)
void addServico (Servico *ser)
void modificaNome (string nome)
void info ()
string getNome ()
Habitacao * getHabitacao (Condomino *cond)
vector< Habitacao * > & getHabitacoes ()
vector< Servico * > & getServicos ()
void OrdenarHabArea ()
void OrdenarHabMorada ()
void OrdenarHabMensalidade ()
void OrdenarServicoCondNome ()
void verHab ()
void verSerCond ()
void remServico (string nome)
void remHab (unsigned int nif)
Servico * getServ (string nome)
Condominio (string nome, string localizacao)
bool operator< (const Condominio &dir) const
int getNumHab () const
string getLocalizacao () const
int getNumVivendas () const
void addTransporte (Transporte &transporte)
bool remTransporte (string tipo)
void toogle_Ativ_PontoParagem (string tipo)
string getPontoParagemMaisProx ()
string getPontoParagemMaisProx (string dest)
void listarTransportes ()
string saveTransportes ()
void addServico_Cond (Servico &servico)
void procurarServicos (string nomeServico)
void listarServicos ()
void remServico_Cond (string nomeServico)
string saveServicos ()
string saveHabitacoes ()
Private Attributes
string Nome
string Localizacao
vector< Habitacao * > Habitacoes
vector< Servico * > Servico_Condominio
hashServicos Servicos_Cond
priority_queue< Transporte > TransportesPublicos
int num_hab
int num_vivendas
Detailed Description
Definition at line 28 of file Condominios.h.
Constructor & Destructor Documentation
Condominio::Condominio (string nome)
Construtor da class Condominio, cria um Condominio com as especificacoes dadas
Parameters
nome Nome (Condominio::Nome)
Definition at line 7 of file Condominios.cpp.
Condominio::Condominio (string nome, string localizacao)
Construtor da Classe com as expecificacoes dadas
Parameters
nome Nome (Condominio::Nome)
Definition at line 9 of file Condominios.cpp.
Member Function Documentation
void Condominio::addHabitacao (Habitacao * hab)
Destrutor da class Condominio Adiciona a Habitacao pretendida ao vector de Habitacoes do Condominio (Condominio::Habitacoes)
Parameters
hab Habitacao pretendida
Definition at line 12 of file Condominios.cpp.
References Habitacao::getCondomino(), Habitacoes, num_hab, and num_vivendas.
void Condominio::addServico (Servico * ser)
Adiciona o Servico pretendido ao vector de servicos do Condominio (Condominio::Servico_Condominio)
Definition at line 26 of file Condominios.cpp.
References Servico::getNome(), getNome(), Servico::getNumPrestServ(), and Servico_Condominio.
void Condominio::addServico_Cond (Servico & servico)
Adiciona o Servico servico ao condominio
Definition at line 259 of file Condominios.cpp.
References Servico::getNumPrestServ(), Servico::modificaNPS(), and Servicos_Cond.
void Condominio::addTransporte (Transporte & transporte)
Adiciona o Transporte transporte;
Definition at line 374 of file Condominios.cpp.
References TransportesPublicos.
Habitacao * Condominio::getHabitacao (Condomino * cond)
Devolve a Habitacao cujo Condominio e o pretendido
Parameters
cond Condominio pretendido
Definition at line 65 of file Condominios.cpp.
References Condomino::getNif(), Condomino::getNome(), getNome(), and Habitacoes.
vector< Habitacao * > & Condominio::getHabitacoes ()
Devolve o vector de habitacoes (Condominio::Habitacoes) do Condominio
Definition at line 76 of file Condominios.cpp.
References Habitacoes.
string Condominio::getLocalizacao () const
Retorna a Localizacao
Definition at line 584 of file Condominios.cpp.
References Localizacao.
Referenced by Data::condLocal(), and Data::info().
string Condominio::getNome ()
Devolve o Nome (Condominio::Nome) do Condominio
Definition at line 60 of file Condominios.cpp.
References Nome.
Referenced by addServico(), Data::condNome(), getHabitacao(), getServ(), Data::info(), and remServico().
int Condominio::getNumHab () const
Retorna o numero de Habitacoes
Definition at line 560 of file Condominios.cpp.
References num_hab.
Referenced by Data::condEntreHab(), Data::condXApartamentos(), Data::condXHab(), Data::info(), and operator<().
int Condominio::getNumVivendas () const
Retorna o numero de Vivendas
Definition at line 565 of file Condominios.cpp.
References num_vivendas.
Referenced by Data::condXApartamentos(), Data::condXVivendas(), and operator<().
string Condominio::getPontoParagemMaisProx ()
Retorna o ponto de paragem mais proximo (sem destino)
Definition at line 380 of file Condominios.cpp.
References TransportesPublicos.
string Condominio::getPontoParagemMaisProx (string dest)
Retorna o ponto de paragem mais proximo com destino dest
Definition at line 406 of file Condominios.cpp.
References TransportesPublicos.
Servico * Condominio::getServ (string nome)
Devolve o Servico do condominio cujo nome é o pretendido
Parameters
nome Nome pretendido
Definition at line 241 of file Condominios.cpp.
References getNome(), and Servico_Condominio.
vector< Servico * > & Condominio::getServicos ()
Devolve o vector de servicos (Condominio::Servico_Condominio) usados pelo Condominio
Definition at line 81 of file Condominios.cpp.
References Servico_Condominio.
void Condominio::info ()
Devolve a informacao sobre o Condominio
Definition at line 41 of file Condominios.cpp.
References Habitacoes, Nome, and Servico_Condominio.
void Condominio::listarServicos ()
Lista os Servicos
Definition at line 306 of file Condominios.cpp.
References Servicos_Cond.
void Condominio::listarTransportes ()
Lista os transportes
Definition at line 469 of file Condominios.cpp.
References TransportesPublicos.
void Condominio::modificaNome (string nome)
Modifica o Nome (Condominio::Nome) do Condominio para o nome pretendido
Parameters
nome Nome pretendido
Definition at line 36 of file Condominios.cpp.
References Nome.
bool Condominio::operator< (const Condominio & dir) const
Overload do operador < para comparacao de condominios
Definition at line 574 of file Condominios.cpp.
References getNumHab(), and getNumVivendas().
void Condominio::OrdenarHabArea ()
Ordena o vector de Habitacoes (Condominio::Habitacoes) por valor de Area (Habitacao::Area_Habitacional) (Crescente)
Definition at line 107 of file Condominios.cpp.
References Habitacoes, and ordhabarea().
Referenced by verHab().
void Condominio::OrdenarHabMensalidade ()
Ordena o vector de Habitacoes (Condominio::Habitacoes) por valor da mensalidade (Habitacao::Mensalidade) (Crescente)
Definition at line 117 of file Condominios.cpp.
References Habitacoes, and ordhabmensalidade().
Referenced by verHab().
void Condominio::OrdenarHabMorada ()
Ordena o vector de Habitacoes (Condominio::Habitacoes) por ordem alfabetica da Morada (Habitacao::Morada) (Crescente)
Definition at line 112 of file Condominios.cpp.
References Habitacoes, and ordhabmorada().
Referenced by verHab().
void Condominio::OrdenarServicoCondNome ()
Ordena o vector de servicos do Condominio (Condominio::Servico_Condominio) por ordem alfabetica do nome (Servico::Nome) (Crescente)
Definition at line 122 of file Condominios.cpp.
References Servico_Condominio.
Referenced by verSerCond().
void Condominio::procurarServicos (string nomeServico)
Procura o servico de nome nomeServico
Definition at line 283 of file Condominios.cpp.
References Servicos_Cond.
void Condominio::remHab (unsigned int nif)
Remove a Habitacao cujo NIF (Condomino::NIF) do Condomino é o pretendido
Parameters
nif NIF pretendido
Definition at line 216 of file Condominios.cpp.
References Habitacoes, num_hab, and num_vivendas.
void Condominio::remServico (string nome)
Remove o Servico cujo nome (Servico::Nome) e o pretendido do vector de servicos de condominio (Condominio::Servico_Condominio)
Parameters
nome Nome pretendido
Definition at line 202 of file Condominios.cpp.
References getNome(), and Servico_Condominio.
void Condominio::remServico_Cond (string nomeServico)
Remove o Servico de nome nomeServico do condominio
Definition at line 323 of file Condominios.cpp.
References Servicos_Cond.
bool Condominio::remTransporte (string tipo)
Remove o Transporte do tipo tipo;
Definition at line 438 of file Condominios.cpp.
References TransportesPublicos.
string Condominio::saveHabitacoes ()
Guarda as alteracoes feitas no que conta a Habitacoes;
Definition at line 589 of file Condominios.cpp.
References Habitacoes.
string Condominio::saveServicos ()
Guarda as alteracoes feitas no que conta a servicos;
Definition at line 345 of file Condominios.cpp.
References Servicos_Cond.
string Condominio::saveTransportes ()
Guarda alteracoes feitas no que conta a transpontes;
Definition at line 523 of file Condominios.cpp.
References TransportesPublicos.
void Condominio::toogle_Ativ_PontoParagem (string tipo)
Ativa/Desativa o Ponto de paragem do tipo tipo;
Definition at line 499 of file Condominios.cpp.
References TransportesPublicos.
void Condominio::verHab ()
Mostra as informacoes das habitacões ordenadas consoante um numero de input; 1-Area , 2-Morada , 3-Mensalidade
Definition at line 143 of file Condominios.cpp.
References Habitacoes, limpa(), num_hab, num_vivendas, OrdenarHabArea(), OrdenarHabMensalidade(), and OrdenarHabMorada().
void Condominio::verSerCond ()
Mostras os nomes (Servico::Nome) dos servicos de condominio (Condominio::Servico_Condominio) ordenados por ordem alfabetica
Definition at line 193 of file Condominios.cpp.
References OrdenarServicoCondNome(), and Servico_Condominio.
Member Data Documentation
vector<Habitacao*> Condominio::Habitacoes private
Vector de Habitacoes do Condominio
Definition at line 203 of file Condominios.h.
Referenced by addHabitacao(), getHabitacao(), getHabitacoes(), info(), OrdenarHabArea(), OrdenarHabMensalidade(), OrdenarHabMorada(), remHab(), saveHabitacoes(), and verHab().
string Condominio::Localizacao private
Localizacao do Condominio
Definition at line 199 of file Condominios.h.
Referenced by getLocalizacao().
string Condominio::Nome private
Nome do Condominio
Definition at line 195 of file Condominios.h.
Referenced by getNome(), info(), and modificaNome().
int Condominio::num_hab private
Numero de Habitacoes do Condominio
Definition at line 220 of file Condominios.h.
Referenced by addHabitacao(), getNumHab(), remHab(), and verHab().
int Condominio::num_vivendas private
Numero de Vivendas do Condominio
Definition at line 224 of file Condominios.h.
Referenced by addHabitacao(), getNumVivendas(), remHab(), and verHab().
vector<Servico *> Condominio::Servico_Condominio private
Vector de Servicos do Condominio
Definition at line 207 of file Condominios.h.
Referenced by addServico(), getServ(), getServicos(), info(), OrdenarServicoCondNome(), remServico(), and verSerCond().
hashServicos Condominio::Servicos_Cond private
Hash de Servicos existentes
Definition at line 212 of file Condominios.h.
Referenced by addServico_Cond(), listarServicos(), procurarServicos(), remServico_Cond(), and saveServicos().
priority_queue<Transporte> Condominio::TransportesPublicos private
Fila de prioridade de Transportes
Definition at line 216 of file Condominios.h.
Referenced by addTransporte(), getPontoParagemMaisProx(), listarTransportes(), remTransporte(), saveTransportes(), and toogle_Ativ_PontoParagem().
The documentation for this class was generated from the following files:
Condominios.h
Condominios.cpp