AEDA_2_FINAL: Condomino Class Reference
Condomino Class Reference
#include <Condomino.h>
Public Member Functions
Condomino (string nome, unsigned int nif)
unsigned int getNif ()
string getNome ()
void modificaNome (string nome)
void modificaNIF (unsigned int nif)
Private Attributes
string Nome
unsigned int NIF
Detailed Description
Definition at line 8 of file Condomino.h.
Constructor & Destructor Documentation
Condomino::Condomino (string nome, unsigned int nif)
Construtor da class Condomino , cria um Condomino com as especificacoes dadas
Parameters
nome Nome do condomino (Condomino::Nome)
nif NIF do condomino (Condomino::NIF)
Definition at line 3 of file Condomino.cpp.
Member Function Documentation
unsigned int Condomino::getNif ()
Devolve NIF (Condomino::NIF) do Condomino
Definition at line 6 of file Condomino.cpp.
References NIF.
Referenced by Condominio::getHabitacao(), Apartamento::info(), and Vivenda::info().
string Condomino::getNome ()
Devolve Nome (Condomino::Nome) do Condomino
Definition at line 11 of file Condomino.cpp.
References Nome.
Referenced by Condominio::getHabitacao(), Apartamento::info(), Vivenda::info(), Apartamento::save(), and Vivenda::save().
void Condomino::modificaNIF (unsigned int nif)
Modifica o NIF do Condomino (Condomino::NIF) para o valor pretendido
Parameters
nif NIF pretendido
Definition at line 20 of file Condomino.cpp.
References NIF.
void Condomino::modificaNome (string nome)
Modifica o nome do Condomino (Condomino::Nome) para o valor pretendido
Parameters
nome Nome pretendido
Definition at line 16 of file Condomino.cpp.
References Nome.
Member Data Documentation
unsigned int Condomino::NIF private
NIF do Condomino
Definition at line 40 of file Condomino.h.
Referenced by getNif(), and modificaNIF().
string Condomino::Nome private
Nome do Condomino
Definition at line 36 of file Condomino.h.
Referenced by getNome(), and modificaNome().
The documentation for this class was generated from the following files:
Condomino.h
Condomino.cpp