AEDA_2_FINAL: Habitacao Class Reference
Habitacao Class Reference abstract
#include <Habitacao.h>
Public Member Functions
Habitacao (string morada, unsigned int area_hab, float mensalidade)
void modificaMensalidade (float mensalidade)
string getMorada ()
unsigned int getA_Habitacional ()
float getMensalidade ()
Condomino * getCondomino ()
vector< Servico * > getServicos ()
void modificaMorada (string morada)
void modificaArea_Habitacional (unsigned int areaHab)
void ordenaServicosNome ()
virtual void info ()=0
virtual void calcMensalidade ()=0
void addCondomino (Condomino *cond)
void addServico (Servico *ser)
void removeServico (Servico *ser)
virtual string save ()
void verServicosAderidos ()
Private Attributes
string Morada
unsigned int Area_Habitacional
float Mensalidade
Condomino * condomino
vector< Servico * > servico
Detailed Description
Definition at line 16 of file Habitacao.h.
Constructor & Destructor Documentation
Habitacao::Habitacao (string morada, unsigned int area_hab, float mensalidade)
Construtor da class Habitacao, cria uma habitacao com as expecificacoes dadas
Parameters
morada Morada (Habitacao::Morada)
area_hab Area da Habitacao (Habitacao::Area_Habitacional)
mensalidade Mensalidade (Habitacao::Mensalidade)
Definition at line 3 of file Habitacao.cpp.
Member Function Documentation
void Habitacao::addCondomino (Condomino * cond)
Modifica o condomino (Habitacao::condomino) da Habitacao para o Condomino pretendido;
Parameters
cond Condomino pretendido
Definition at line 6 of file Habitacao.cpp.
References condomino.
Referenced by Menu::Hab_op1_apartamento(), Menu::Hab_op1_vivenda(), and Data::inicialize().
void Habitacao::addServico (Servico * ser)
Adiciona um Servico ao vector de servicos (Habitacao::servico) da Habitacao
Parameters
ser Servico a ser adicionado
Definition at line 11 of file Habitacao.cpp.
References Servico::decNserv(), Servico::getNome(), Servico::getNumPrestServ(), getServicos(), and servico.
Referenced by Menu::Hab_op3_Aderir_Servico(), and Data::inicialize().
virtual void Habitacao::calcMensalidade () pure virtual
Metodo virtual para ser modificado pelas sub-classes (Vivenda e Apartamento) que calcula a sua mensalidade
Implemented in Vivenda, and Apartamento.
Referenced by Menu::Hab_op1_apartamento(), and Menu::Hab_op1_vivenda().
unsigned int Habitacao::getA_Habitacional ()
Devolve a Area Habitacional (Habitacao::Area_Habitacional) da Habitacao
Definition at line 41 of file Habitacao.cpp.
References Area_Habitacional.
Referenced by Apartamento::calcMensalidade(), Vivenda::calcMensalidade(), Apartamento::info(), Vivenda::info(), ordhabarea(), Apartamento::save(), and Vivenda::save().
Condomino * Habitacao::getCondomino ()
Devolve o condomino (Habitacao::condomino) da Habitacao
Definition at line 51 of file Habitacao.cpp.
References condomino.
Referenced by Condominio::addHabitacao(), Apartamento::info(), Vivenda::info(), Apartamento::save(), and Vivenda::save().
float Habitacao::getMensalidade ()
Devolve a Mensalidade (Habitacao::Mensalidade) da Habitacao
Definition at line 46 of file Habitacao.cpp.
References Mensalidade.
Referenced by Apartamento::calcMensalidade(), Vivenda::calcMensalidade(), Apartamento::info(), Vivenda::info(), ordhabmensalidade(), Apartamento::save(), and Vivenda::save().
string Habitacao::getMorada ()
Devolve a Morada (Habitacao::Morada) da Habitacao
Definition at line 36 of file Habitacao.cpp.
References Morada.
Referenced by Apartamento::info(), Vivenda::info(), ordhabmorada(), Apartamento::save(), and Vivenda::save().
vector< Servico * > Habitacao::getServicos ()
Devolve um vector com os servicos (Habitacao::servico) da Habitacao
Definition at line 56 of file Habitacao.cpp.
References servico.
Referenced by addServico(), Apartamento::info(), Vivenda::info(), Apartamento::save(), and Vivenda::save().
virtual void Habitacao::info () pure virtual
Metodo virtual para ser modificado pelas sub-classes (Vivenda e Apartamento) que devolve a sua informacao
Implemented in Vivenda, and Apartamento.
void Habitacao::modificaArea_Habitacional (unsigned int areaHab)
Modifica a Area Habitacional (Habitacao::Area_Habitacional) para o valor pretendido
Parameters
areaHab Valor pretendido da Area Habitacional (Habitacao::Area_Habitacional)
Definition at line 66 of file Habitacao.cpp.
References Area_Habitacional.
Referenced by Menu::Hab_op3_Mod_AreaHabitacional().
void Habitacao::modificaMensalidade (float mensalidade)
Modifica o valor da mensalidade (Habitacao::Mensalidade) para o valor pretendido
Parameters
mensalidade Mensalidade pretendida
Definition at line 27 of file Habitacao.cpp.
References Mensalidade.
Referenced by Apartamento::calcMensalidade(), Vivenda::calcMensalidade(), and Menu::Hab_op3_Mod_Mensalidade().
void Habitacao::modificaMorada (string morada)
Modifica a Morada (Habitacao::Morada) para o valor pretendido
Parameters
morada Valor pretendido da Morada (Habitacao::Morada)
Definition at line 61 of file Habitacao.cpp.
References Morada.
void Habitacao::ordenaServicosNome ()
Ordena o vector com os servicos (Habitacao::servico) da Habitacao por ordem alfabetica do nome (Servico::Nome)
Definition at line 91 of file Habitacao.cpp.
References servico.
Referenced by verServicosAderidos().
void Habitacao::removeServico (Servico * ser)
Remove o Servico pretendido do vector de servicos (Habitacao::servico) da Habitacao
Parameters
ser Servico a ser removido
Definition at line 71 of file Habitacao.cpp.
References Servico::addNserv(), Servico::getNome(), and servico.
Referenced by Menu::Hab_op3_Terminar_Servico().
virtual string Habitacao::save () inline virtual
Funcao Virual para ser modificada por Apartamento e Vivenda
Reimplemented in Vivenda, and Apartamento.
Definition at line 82 of file Habitacao.h.
void Habitacao::verServicosAderidos ()
Mostra todos os servicos aderidos pela habitacao
Definition at line 98 of file Habitacao.cpp.
References ordenaServicosNome(), and servico.
Referenced by Menu::Hab_op3_Terminar_Servico().
Member Data Documentation
unsigned int Habitacao::Area_Habitacional private
Area Habitacional da Habitacao
Definition at line 97 of file Habitacao.h.
Referenced by getA_Habitacional(), and modificaArea_Habitacional().
Condomino* Habitacao::condomino private
Condomino da Habitacao
Definition at line 105 of file Habitacao.h.
Referenced by addCondomino(), and getCondomino().
float Habitacao::Mensalidade private
Mensalidade da Habitacao
Definition at line 101 of file Habitacao.h.
Referenced by getMensalidade(), and modificaMensalidade().
string Habitacao::Morada private
Morada da Habitacao
Definition at line 93 of file Habitacao.h.
Referenced by getMorada(), and modificaMorada().
vector<Servico *> Habitacao::servico private
Vector de Servicos da Habitacao
Definition at line 109 of file Habitacao.h.
Referenced by addServico(), getServicos(), ordenaServicosNome(), removeServico(), and verServicosAderidos().
The documentation for this class was generated from the following files:
Habitacao.h
Habitacao.cpp