AEDA_PROJECTO_1: Data.cpp File Reference
Data.cpp File Reference
#include "Data.h"
#include <fstream>
#include <sstream>
#include <iostream>
#include <Windows.h>
Functions
template<class T >
T string_to_int (string intStr)
void clrscr2 ()
bool verificaOPi (string opcao)
bool verificaHab (string opcao)
bool verificaTip (string opcao)
bool verificaOp2 (string opcao)
Function Documentation
void clrscr2 ()
Definition at line 345 of file Data.cpp.
Referenced by Data::run().
template<class T > T string_to_int (string intStr)
Definition at line 11 of file Data.cpp.
bool verificaHab (string opcao)
Definition at line 366 of file Data.cpp.
Referenced by Data::run().
bool verificaOp2 (string opcao)
Definition at line 382 of file Data.cpp.
Referenced by Data::run().
bool verificaOPi (string opcao)
Definition at line 358 of file Data.cpp.
Referenced by Data::run().
bool verificaTip (string opcao)
Definition at line 374 of file Data.cpp.
Referenced by Data::run().