AEDA_PROJECTO_1: Servico Class Reference
Servico Class Reference
#include <Servicos.h>
Public Member Functions
Servico (string nome, unsigned int nPresServ)
~Servico ()
string getNome ()
unsigned int getNumPrestServ ()
void modificaNome (string nome)
void addNserv ()
void decNserv ()
bool operator< (Servico &b)
void modificaNPS (unsigned int num)
Servico (string nome, unsigned int nPresServ, int ident)
int getId ()
string save ()
Private Attributes
string Nome
unsigned int numPrestServ
int id
Detailed Description
Definition at line 9 of file Servicos.h.
Constructor & Destructor Documentation
Servico::Servico (string nome, unsigned int nPresServ)
Construtor da class Servico ,cria um Servico com as expecificacoes dadas
Parameters
nome Nome do Servico (Servico::Nome)
nPresServ Numero de Prestadores de Servico (Servico::numPrestServ)
Definition at line 3 of file Servicos.cpp.
Servico::~Servico ()
Destrutor da class Servico
Servico::Servico (string nome, unsigned int nPresServ, int ident)
54 * Construtor da class Servico ,cria um Servico com as expecificacoes dadas (com identificador de servico (Servico::id)) 55
Parameters
nome Nome do Servico (Servico::Nome)
nPresServ Numero de Prestadores de Servico (Servico::numPrestServ)
ident Identificador do Serviço
Definition at line 51 of file Servicos.cpp.
Member Function Documentation
void Servico::addNserv ()
Adiciona um Prestador de servico (Servico::numPrestServ)
Definition at line 21 of file Servicos.cpp.
References numPrestServ.
Referenced by Habitacao::removeServico().
void Servico::decNserv ()
Retira um Prestador de servico (Servico::numPrestServ)
Definition at line 26 of file Servicos.cpp.
References numPrestServ.
Referenced by Habitacao::addServico().
int Servico::getId ()
Retorna o identificador do Servio (Servico::id)
Definition at line 40 of file Servicos.cpp.
References id.
string Servico::getNome ()
Devolve o nome do Servico (Servico::Nome)
Definition at line 6 of file Servicos.cpp.
References Nome.
Referenced by Condominio::addServico(), Habitacao::addServico(), operator<(), and Habitacao::removeServico().
unsigned int Servico::getNumPrestServ ()
Devolve o Numero de Prestadores do Servico (Servico::numPrestServ)
Definition at line 11 of file Servicos.cpp.
References numPrestServ.
Referenced by Habitacao::addServico().
void Servico::modificaNome (string nome)
Altera o nome (Servico::Nome) do Servico para o nome dado
Parameters
nome Nome do Servico
Definition at line 16 of file Servicos.cpp.
References Nome.
Referenced by Data::run().
void Servico::modificaNPS (unsigned int num)
Modifica numero de prestadores (Servico::numPrestServ) para o numero pretendido
Parameters
num Numero pretendido
Definition at line 33 of file Servicos.cpp.
References numPrestServ.
Referenced by Data::run().
bool Servico::operator< (Servico & b) inline
Overload do operador < de forma a ordenar os servicos por ordem alfabetica do nome
Definition at line 43 of file Servicos.h.
References getNome().
string Servico::save ()
Guarda a informacao
Definition at line 45 of file Servicos.cpp.
References Nome, and numPrestServ.
Member Data Documentation
int Servico::id private
Identificador de Servico
Definition at line 81 of file Servicos.h.
Referenced by getId().
string Servico::Nome private
Nome do Servico
Definition at line 72 of file Servicos.h.
Referenced by getNome(), modificaNome(), and save().
unsigned int Servico::numPrestServ private
Numero de prestadores desse Servico
Definition at line 76 of file Servicos.h.
Referenced by addNserv(), decNserv(), getNumPrestServ(), modificaNPS(), and save().
The documentation for this class was generated from the following files:
Servicos.h
Servicos.cpp