AEDA_PROJECTO_1: Apartamento Class Reference
Apartamento Class Reference
#include <Apartamento.h>
Public Member Functions
Apartamento (std::string morada, unsigned int area_hab, float mensalidade, std::string tipo, int piso)
void info ()
void calcMensalidade ()
string getTipologia ()
int getPiso ()
void modificaTipologia (string tipo)
void modificaPiso (int piso)
string save ()
Public Member Functions inherited from Habitacao
Habitacao (string morada, unsigned int area_hab, float mensalidade)
void modificaMensalidade (float mensalidade)
string getMorada ()
unsigned int getA_Habitacional ()
float getMensalidade ()
Condomino * getCondomino ()
vector< Servico * > getServicos ()
void modificaMorada (string morada)
void modificaArea_Habitacional (unsigned int areaHab)
void ordenaServicosNome ()
void addCondomino (Condomino *cond)
void addServico (Servico *ser)
void removeServico (Servico *ser)
void verServicosAderidos ()
Private Attributes
string Tipologia
int Piso
Detailed Description
Definition at line 6 of file Apartamento.h.
Constructor & Destructor Documentation
Apartamento::Apartamento (std::string morada, unsigned int area_hab, float mensalidade, std::string tipo, int piso)
Constructor da class Apartamento, cria um Apartamento com as expecificacoes dadas
Parameters
morada Morada (Habitacao::Morada)
area_hab Area Habitacional (Habitacao::Area_Habitacional)
mensalidade Mensalidade (Habitacao::Mensalidade)
tipo Tipologia (Apartamento::Tipologia)
piso Piso (Apartamento::Piso)
Definition at line 4 of file Apartamento.cpp.
Member Function Documentation
void Apartamento::calcMensalidade () virtual
Calcula a Mensalidade (Habitacao::Mensalidade) do Apartamento
Implements Habitacao.
Definition at line 23 of file Apartamento.cpp.
References Habitacao::getA_Habitacional(), Habitacao::getMensalidade(), getPiso(), getTipologia(), and Habitacao::modificaMensalidade().
int Apartamento::getPiso ()
Devolve o Piso (Apartamento::Piso) do Apartamento
Definition at line 69 of file Apartamento.cpp.
References Piso.
Referenced by calcMensalidade(), info(), and save().
string Apartamento::getTipologia ()
Devolve a Tipologia (Apartamento::Tipologia) do Apartamento
Definition at line 64 of file Apartamento.cpp.
References Tipologia.
Referenced by calcMensalidade(), info(), and save().
void Apartamento::info () virtual
Devolve a informacao sobre o Apartamento
Implements Habitacao.
Definition at line 7 of file Apartamento.cpp.
References Habitacao::getA_Habitacional(), Habitacao::getCondomino(), Habitacao::getMensalidade(), Habitacao::getMorada(), Condomino::getNif(), Condomino::getNome(), getPiso(), Habitacao::getServicos(), and getTipologia().
void Apartamento::modificaPiso (int piso)
Modifica o Piso (Apartamento::Piso) do Apartamento para o valor pretendido
Parameters
piso Piso pretendido
Definition at line 79 of file Apartamento.cpp.
References Piso.
void Apartamento::modificaTipologia (string tipo)
Modifica a Tipologia (Apartamento::Tipologia) do Apartamento para o valor pretendido
Parameters
tipo Tipologia pretendida
Definition at line 74 of file Apartamento.cpp.
References Tipologia.
string Apartamento::save () virtual
Guarda a informacao
Reimplemented from Habitacao.
Definition at line 84 of file Apartamento.cpp.
References Habitacao::getA_Habitacional(), Habitacao::getCondomino(), Habitacao::getMensalidade(), Habitacao::getMorada(), getPiso(), Habitacao::getServicos(), and getTipologia().
Member Data Documentation
int Apartamento::Piso private
Piso do Apartamento
Definition at line 53 of file Apartamento.h.
Referenced by getPiso(), and modificaPiso().
string Apartamento::Tipologia private
Tipologia do Apartamento, T0,T1,T2,T3,... maximo T10
Definition at line 49 of file Apartamento.h.
Referenced by getTipologia(), and modificaTipologia().
The documentation for this class was generated from the following files:
Apartamento.h
Apartamento.cpp